version: '3.8'

services:
  db:
    image: mariadb:11.2.2
    env_file:
      - ./.env
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - ingame

volumes:
  mariadb_data:

networks:
  ingame:
    name: ingame
