version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./client/.env
    depends_on:
      - server
    networks:
      - ingame

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - '8080:8080'
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./server/.development.env
    networks:
      - ingame

networks:
  ingame:
    external: true
    name: ingame
