name: Backend CI

on:
  pull_request:
    branches: [dev]
    paths:
      - 'server/**'

env:
  working-directory: ./server

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: ${{ env.working-directory }}/package-lock.json

      - name: Install Dependencies
        run: npm ci

      - name: Run test
        run: npm run test

      - name: Run build
        run: npm run build
